### ISSUE TITLE
Var_loop_lay_table not being initialized for certain configurations

### ISSUE THREAD

**Issue by lawfordp2017** [srlabUsask/crhmcode#308]
I'm trying to get the waterquality modules functioning but having some difficulties.
In ClassModule.cpp method initbase() line 72 Var_loop_lay_table gets initialized if Var_NDEFN_cnt > 0.
I'm having some problems with this:

first, I can't find this code in the Borland version from 2019. I'm wondering where the code came from.
second,  the decl and init tasks are not occuring in the proper order so the Var_NDEFN_cnt is not set properly, the Var_loop_lay_table never gets initialized, and later on during initialization at ClassModule.cpp:427 I get a segfault.

I can provide a project file but it may require using the waterquality_updates branch to run, so maybe first we could focus on why Var_loop_lay_table exists in the first place, when it got added in, or whether it is even necessary.

**Comment by jhs507** [comment]
@lawfordp2017 Can you give me an update on this issue?

**Comment by DiogoCostaPT** [comment]
Hi @lawfordp2017 

Good to hear from you. I haven't worked with this for a few years. 
Can you please give me more precise instructions on the clarifications you need and how I can help you with this issue?

**Comment by DiogoCostaPT** [comment]
perfect

From: jhs507 ***@***.***>
Date: Tuesday, 4 June 2024 at 16:58
To: srlabUsask/crhmcode ***@***.***>
Cc: Diogo Costa ***@***.***>, Mention ***@***.***>
Subject: Re: [srlabUsask/crhmcode] Var_loop_lay_table not being initialized for certain configurations (Issue #308)

Closed #308<https://github.com/srlabUsask/crhmcode/issues/308> as completed.
