### ISSUE TITLE
"No Model Output selected" error

### ISSUE THREAD

**Issue by tmahmood469** [srlabUsask/crhmcode#416]
I tried to run ./crhm smithcreek_2014.prj and it gives error "No Model Output selected"..
This prj file is provided with the crhmcode in prj folder.. I checked the prj file and display variable is there in line 2108.. Please see below
Display_Variable:
######
REW_Grp WS_flow@F 1
REW_Grp WS_flow_s@F 1
REW_Grp WS_gwflow@F 1
REW_Grp WS_inflow@F 1
REW_Grp WS_outflow@F 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpA hru_t@A 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpC hru_t@C 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpE hru_t@E 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpA net_p@A 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpC net_p@C 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpE net_p@E 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpD hru_t@D 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpE net_p@E 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpB hru_evap@B 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpB hru_rain@B 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpB hru_p@B 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpB hru_snow@B 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpA hru_rh@A 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpA Pa@A 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpA hru_tmean@A 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpA runoff@A 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpC runoff@C 1
SmithCreekBasin_GroupTemplate_Modified_20Oct_GrpE runoff@E 1
######
Display_Observation:

**Comment by BZ840** [comment]
[obs.txt](https://github.com/srlabUsask/crhmcode/files/11392519/obs.txt)
[Basin.txt](https://github.com/srlabUsask/crhmcode/files/11392520/Basin.txt)
[One_subbasin.txt](https://github.com/srlabUsask/crhmcode/files/11392521/One_subbasin.txt)

Hi @jhs507, here I have two proj files: one_subbasin and basin (which has 3 sub-basins grouped). The GUI (latest version) had no problem running the one_subbasin.prj, but it kept crushing (autoexit) with the msg "No model output selected" when running the basin.prj. I am not sure what is causing the issue, can you please take a look?

**Comment by jhs507** [comment]
@BZ840 

Could you open a new issue detailing the bug you have encountered? I think what you are experiencing is different than this original error. 

Also could you please delete crhmRun.log, then attempt running one of these models, then upload the crhmRun.log file as well it may help me find the issue.
