### ISSUE TITLE
Problem with installing the CLI crhm on Windows

### ISSUE THREAD

**Issue by loganxingfang** [srlabUsask/crhmcode#421]
I got an email from a user trying to installing the CLI crhm on Windows using the instruction from https://github.com/srlabUsask/crhmcode/wiki/Building-CRHMcode-GCC#windows

The user had a message showing in the **Installing the executable** when running "make install", the installation fails and it says "No rule to make target install" Stop. msys2.

I tried to repeat this on my Windows and had the same message shown when running  "make install" in the **Installing the executable**, the message I got is:

make: *** No rule to make target 'install'.  Stop.

Another thing I noticed is that there is no crhm executable contained in build folder, as mentioned in Step 10 once Steps 8 and 9 were done. I have the screen shot here showing the files generated after Steps 8 and 9, there is no crhm executable.
![screen shot for CLI build](https://user-images.githubusercontent.com/28319889/193945028-68e888e4-710c-448d-bc26-2eec84fe5599.png)

**Comment by jhs507** [comment]
To use command line CRHM on windows you can simply use the GUI executable within windows command prompt or powershell.

From the looks of it cmake is defaulting to using a different compiler than gcc and that is causing problems for you when you try to build it from source natively on windows. 

Try adding these flags to your cmake commands. 
`-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++`

**Comment by loganxingfang** [comment]
> Try adding these flags to your cmake commands.
> `-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++`

Which Step should this be added, Step 8 or Step 9?

**Comment by jhs507** [comment]
I think adding them on both steps would be best.

**Comment by loganxingfang** [comment]
1. **I added -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ to Step 8:**

C:\Research\GitHub\crhmcode\crhmcode\build>cmake ../src -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30137.0
-- The CXX compiler identification is MSVC 19.29.30137.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Research/GitHub/crhmcode/crhmcode/build

2. **I added -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ to Step 9:**

C:\Research\GitHub\crhmcode\crhmcode\build>cmake --build . -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
Unknown argument -DCMAKE_C_COMPILER=gcc
Usage: cmake --build <dir>             [options] [-- [native-options]]
       cmake --build --preset <preset> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --preset <preset>, --preset=<preset>
                 = Specify a build preset.
  --list-presets
                 = List available build presets.
  --parallel [<jobs>], -j [<jobs>]
                 = Build in parallel using the given number of jobs.
                   If <jobs> is omitted the native build tool's
                   default number is used.
                   The CMAKE_BUILD_PARALLEL_LEVEL environment variable
                   specifies a default parallel level when this option
                   is not given.
  --target <tgt>..., -t <tgt>...
                 = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --resolve-package-references={on|only|off}
                 = Restore/resolve package references during build.
  --verbose, -v  = Enable verbose output - if supported - including
                   the build commands to be executed.
  --             = Pass remaining options to the native tool.

Adding -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ to Step 9 did not do anything, as shown above.

3. **So, I just did Step 9 without adding -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++**

I pasted a file from what I got from cmd for this.
[cmake commands_step9.txt](https://github.com/srlabUsask/crhmcode/files/9718481/cmake.commands_step9.txt)

In above attached file, I noticed an error from Line 798 to Line 803:

  CRHMLogger.cpp
  CRHMmain.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\atlmfc\include\afx.h(24,1): fat
al error C1189: #error:  Building MFC application with /MD[d] (CRT dll version) requires MFC shared dll version. Please
 #define _AFXDLL or do not use /MD[d] [C:\Research\GitHub\crhmcode\crhmcode\build\core\core.vcxproj]
  GlobalDll.cpp

**Comment by loganxingfang** [comment]
I think the cmake from cmd invoked Visual Studio 16 2019

**Comment by jhs507** [comment]
Yes it is trying to build the windows executable which is not what we want. One of the version flags must not be set quite right. I will have to investigate. 

Until I have time to look it over will using the CLI provided by the CRHM_GUI.exe be sufficient?

**Comment by loganxingfang** [comment]
Thanks Justin.  I was also to reproduce the other user's CLI installation on Windows problem to find a solution for that.

No problem at the moment with using CRHM_GUI on Windows. I think we still have the evaluation version of the TeeChart, as the water mark is still on CRHM_GUI.

**Comment by jhs507** [comment]
Yes we still have the evaluation version.

**Comment by jhs507** [comment]
I have started to move towards a fix for this but I have been unable to finish it completely. 

In step 8 I have instead used:
` cmake ../src/ -G "MSYS Makefiles"`

This will direct CMAKE to use the correct generator for the make files. 

Additionally I had to alter Common.h line 39 to read
`#if defined(__linux__) || defined(__APPLE__) || defined(__CYGWIN__) `

All of the modules seemed to compile correctly after these changes. However it seems that msys/mingw64 doesn't play well with building SPDLOG. We should be able to remedy this by using a static linked spdlog header file on this build but that will require a few more alterations.

**Comment by loganxingfang** [comment]
Thanks Justin. For both Step 8 and 9, I called cmake on Command Prompt, as I was not able to install mingw-w64-x86_64-cmake package for mingw-w64 console and the installation attempts failed due to some corrupted files yesterday.

Instead, I installed cmake-3.24.2-windows-x86_64 directly on my Windows and set the installation path properly, and called camke from Command Prompt.
