### ISSUE TITLE
Infiltration when ZDF == 0. 

### ISSUE THREAD

**Issue by Bdish22** [srlabUsask/crhmcode#435]
A bug was found where when all the freezing and thawing fronts are equal to zero, all precipitation is directed to runoff and not allowed to infiltrate. This is because _thaw_layers_lay_ is set to 0 during this period (instead of 1), which reduces possible infiltration to 0 and re-allocates it to runoff. 

Below is a modification to the SoilX that solves the issue, and allows infiltration to occur when zd_front_array is equal to 0.

` for (long ll = 0; ll < depths_size; ++ll)
                if (NO_Freeze[hh] || Zd_front_array[0][hh] == 0) //bdisher, 2023 - modification to allow infiltration of precipitatio  
                                                                                                                                                                    when zd_front_array == 0
                //if (NO_Freeze[hh]) 
                    thaw_layers_lay[ll][hh] = 1.0; // all unfrozen
                else
                    thaw_layers_lay[ll][hh] = 0.0; // all frozen`

**Comment by Bdish22** [comment]
The bug occurs in the soilX module.

**Comment by jhs507** [comment]
Thank you for finding this,

The best way to introduce this fix into the main branch will be the following.

1. Create a new branch labeled so that it is associated with this issue ie "issue_435_fix"
2. Implement your fix on the issue_435_fix branch
3. Commit and push your changes
4. Create a pull request to merge the issue_435_fix into the master branch
5. Other contributors will review your changes and then we can merge it into the master branch

Let me know if you need assistance with this.

**Comment by Bdish22** [comment]
Hello,

Sorry for the delay in pushing the fix. When I try and push the new branch to the repo, I get a permission denied notification. Is this an issue on my end, or is permission required to write to the repo?

**Comment by jhs507** [comment]
Sorry yes I forgot you will need to create a fork, the proper way to do this fix will be the following.

1. Create a fork of the crhmcode repository.
2. Create a branch on on that new fork.
3. Implement your fix.
4. Commit and push your changes to your fork.
5. Create a pull request to merge your fork.

If this process doesn't work let me know and I will double check the permissions associated with the repository.

**Comment by jhs507** [comment]
@Bdish22 Were you able to have success creating a fork with your fix?
