### ISSUE TITLE
"Manage Parameter Localy" button for module with variation

### ISSUE THREAD

**Issue by loganxingfang** [srlabUsask/crhmcode#438]
I noticed there is a bug for Parameters GUI. I have a "Example_prj_CRHM_GUI_build_saved.prj" here  to demonstrate this bug. 
[Example_prj_CRHM_GUI_build_saved.zip](https://github.com/srlabUsask/crhmcode/files/13430127/Example_prj_CRHM_GUI_build_saved.zip)

1) When I hit "Manage Parameter Localy" button for parameter Zwind from module CanopyClearingGap#3, CRHM_GUI crashed. See the screen shot here
![screen shot 1](https://github.com/srlabUsask/crhmcode/assets/28319889/9da8f9b5-a13b-4295-bc9f-38ce82570ffd)

2) Similarly, when I hit "Manage Parameter Localy" button for parameter hru_area from module SnobalCRHM#1, CRHM_GUI crashed. See the screen shot here
![screen shot 2](https://github.com/srlabUsask/crhmcode/assets/28319889/2d3220c6-8fbd-4294-bae3-f524d29139bc)

3) When I hit "Manage Parameter Localy" button for parameter hru_area from module frozenAyers, CRHM_GUI allowed me to edit and change values for hru_area. See the screen shots here
![screen shot 3](https://github.com/srlabUsask/crhmcode/assets/28319889/5555dfa8-6ff2-4593-81f6-44a1581e7e05)
![screen shot 4](https://github.com/srlabUsask/crhmcode/assets/28319889/5186cdb9-755d-4f28-86ac-1c3f17bd58f9)

I think there might be missing code to handle "Manage Parameter Localy" for modules with variation, as demonstrated in above 1) and 2).

**Comment by jhs507** [comment]
I will take a look at this sometime this week.
