### ISSUE TITLE
CRHM GroupEnding name in AZ, BZ, CZ, DZ etc

### ISSUE THREAD

**Issue by loganxingfang** [srlabUsask/crhmcode#442]
I have a CRHM user that is running a CRHM group prj. The group prj has 150 groups, ie. from Grp@A to GrpET, and when the group prj finished simulation and saved output, the variables in Sub052_Grp@AZ , Sub078_Grp@BZ, Sub104_Grp@CZ, Sub130_Grp@DZ cannot be saved in the output. I think there is some code missing in crhmcode that handles the large number of groups, ie. missing code to build and read these groups. I attached the group prj along with obs files used here
[obs_files_CMFD_20072008.zip](https://github.com/srlabUsask/crhmcode/files/15300608/obs_files_CMFD_20072008.zip)

Borland CRHM had this issue before it was fixed in February 2019. I am not the original programmer that fixed this, but I believe there are two files in borland_source folder:

CRHMmain.cpp (https://github.com/srlabUsask/crhmcode/blob/master/borland_source/CRHMmain.cpp)

Common.cpp (https://github.com/srlabUsask/crhmcode/blob/master/borland_source/Common.cpp)

In both files, there are codes for GroupEnding. I am not sure how these are coded in crhmcode.

**Comment by jhs507** [comment]
Looks like this is as you suspected a case of code not getting updated between versions. 

This is the code for group endings in borland 
```
void GroupEnding(string &AA, int Cnt){
  int alphas = Cnt/26;
  int letter = Cnt%26;
  if(!letter){ // 26th letter is 'Z' not "@@"
    letter = 26;
    alphas -= 1;
  }
  AA = "@@";
  AA[1] += letter;
  if(alphas > 0){
    string B = "@";
    B[0] += alphas;
    AA.insert(1, B);
  }
}
```

This is the code in crhmcode:
```
void Common::GroupEnding(string &AA, int Cnt) {

	int alphas = Cnt / 26;
	int letter = Cnt % 26;
	if (!letter) { // 26th letter is 'Z' not "@@"
		letter = 26;
		alphas = 0;
	}
	AA = "@@";
	AA[1] += letter;
	if (alphas > 0) {
		string B = "@";
		B[0] += alphas;
		AA.insert(1, B);
	}
}
```

Looks like an easy fix to just add the code that allows for AZ BZ ect to be generated as group endings. I will implement it and send you a version of CRHM with the fix for you to verify it.

**Comment by loganxingfang** [comment]
> Looks like this is as you suspected a case of code not getting updated between versions.
> 
> This is the code for group endings in borland
> 
> ```
> void GroupEnding(string &AA, int Cnt){
>   int alphas = Cnt/26;
>   int letter = Cnt%26;
>   if(!letter){ // 26th letter is 'Z' not "@@"
>     letter = 26;
>     alphas -= 1;
>   }
>   AA = "@@";
>   AA[1] += letter;
>   if(alphas > 0){
>     string B = "@";
>     B[0] += alphas;
>     AA.insert(1, B);
>   }
> }
> ```
> 
> This is the code in crhmcode:
> 
> ```
> void Common::GroupEnding(string &AA, int Cnt) {
> 
> 	int alphas = Cnt / 26;
> 	int letter = Cnt % 26;
> 	if (!letter) { // 26th letter is 'Z' not "@@"
> 		letter = 26;
> 		alphas = 0;
> 	}
> 	AA = "@@";
> 	AA[1] += letter;
> 	if (alphas > 0) {
> 		string B = "@";
> 		B[0] += alphas;
> 		AA.insert(1, B);
> 	}
> }
> ```
> 
> Looks like an easy fix to just add the code that allows for AZ BZ ect to be generated as group endings. I will implement it and send you a version of CRHM with the fix for you to verify it.

In the Borland [Common.cpp](https://github.com/srlabUsask/crhmcode/blob/master/borland_source/Common.cpp) file, there are two blocks of code for GroupEndings


Block 1 from line 20 to 34,
void GroupEnding(string &AA, int Cnt){
  int alphas = Cnt/26;
  int letter = Cnt%26;
  if(!letter){ // 26th letter is 'Z' not "@@"
    letter = 26;
    alphas -= 1;
  }
  AA = "@@";
  AA[1] += letter;
  if(alphas > 0){
    string B = "@";
    B[0] += alphas;
    AA.insert(1, B);
  }
}

Blocks 2 from line 36 to 52,
void GroupEnding(String &AA, int Cnt){
  int alphas = Cnt/26;
  int letter = Cnt%26;

  if(!letter){ // 26th letter is 'Z' not "@@"
    letter = 26;
    alphas -= 1;
  }

  AA = "@@";
  AA[2] += letter;
  if(alphas > 0){
    String B = "@";
    B[1] += alphas;
    AA.Insert(B, 2);
  }
}

Would the block 2 be also needed in crhmcode Common.cpp file?

**Comment by jhs507** [comment]
Yes I noticed that and didn't know what to make of it. They have the exact same signatures so it doesn't make sense for both of them to be present. Looking them over I suspect that the first one is the correct definition and I can't imagine that borland crhm is using both somehow.

**Comment by loganxingfang** [comment]
> Yes I noticed that and didn't know what to make of it. They have the exact same signatures so it doesn't make sense for both of them to be present. Looking them over I suspect that the first one is the correct definition and I can't imagine that borland crhm is using both somehow.

What I noticed the differences are:

In the first blocks, these are used:

AA[1] += letter; 

B[0] += alphas;

AA.insert(1, B);

While in the second block, these are used:

AA[2] += letter;

B[1] += alphas;

AA.Insert(B, 2);

**Comment by jhs507** [comment]
Yes, the second code doesn't make sense to me as it adds the group letters after @@ instead of after a single @

**Comment by jhs507** [comment]
In general I don't like how this code handles adding to strings as it makes the code quite hard to read.

**Comment by jhs507** [comment]
Let me know how the test goes with the version I sent you.

**Comment by loganxingfang** [comment]
> Let me know how the test goes with the version I sent you.

Thanks Justin. I will pass on that installation file to the CRHM user and will let you know how this version does.

**Comment by loganxingfang** [comment]
> Let me know how the test goes with the version I sent you.

@jhs507 I got feedback and see the following:

"I tested the new version of CRHM on group running. It failed, there is no error message. The software just closed by itself without any output. 

I think it may be caused by the different versions. But I reset the group running from the very beginning. The same problem appears.

It could run at one single subbasin.

 

The new version has no End Date in the platform. It may also have limited output variables. When I set the group using Macro, it seems that only I can select the subbasin, but could not enter any words in the Macro."

**Comment by jhs507** [comment]
I am a little confused by this feedback. If the researcher could reply directly here that may be helpful. 

I attempted to run it myself and found that because it was trying to add over 1000 series to the TChart Display this caused an error. There is feedback in CRHMcode GUI that advises the user that when they have selected over 200 inputs that it can become unstable. I think this is a case of that causing issues. I would advise attempting to run this in CRHMcode gcc or without using the GUI to see if it can produce expected results as CRHMcode GUI is not intended to be able to display so many outputs on the graph. 

> I think it may be caused by the different versions. But I reset the group running from the very beginning. The same problem appears.

I don't understand this comment what was reset?

> The new version has no End Date in the platform. It may also have limited output variables. When I set the group using Macro, it seems that only I can select the subbasin, but could not enter any words in the Macro

I also don't understand this comment, what is meant by no End Date in the platform and what is meant by can not enter words in the Macro. 

Would it be possible to test a more simple model that still has groups up to AZ, BZ, CZ ect? as I would like to confirm that the group ending fix I implemented worked before trying to address other possible issues.

**Comment by liudilena** [comment]
Thanks for the help. @jhs507 @loganxingfang 
I attached the potential problems here.
[problems_CRHM.docx](https://github.com/srlabUsask/crhmcode/files/15461710/problems_CRHM.docx)

**Comment by jhs507** [comment]
I am a bit confused does the GUI just cut off after the start_date in the bottom left panel? But in the standard release version it is fine? I did not change anything that should affect the GUI's display. 

With the Macros problem did you have this issue in the previous version of the software as well or just in the new version sent for testing this problem?

**Comment by liudilena** [comment]
The version sent for testing works well for the single basin run, but cut off with the group run. This happens with the latest released version. But the original distribution version has no such problem.
For the Macro problems, only happened in the new testing version.

**Comment by liudilena** [comment]
The issue of @AZ @BZ is solved. The Srlab CRHM code sent for testing issue 442 could run with limited (within 200) variables. 
![image](https://github.com/srlabUsask/crhmcode/assets/94727745/2918bf16-7361-41f7-901e-1b5e35faef7e)

The new problem is that the Macro seems to be locked, could not add anything after the 'end".
![image](https://github.com/srlabUsask/crhmcode/assets/94727745/e02578db-5f6e-41f8-82ce-cd6c49dd57e3)

**Comment by loganxingfang** [comment]
> The version sent for testing works well for the single basin run, but cut off with the group run. This happens with the latest released version. But the original distribution version has no such problem. For the Macro problems, only happened in the new testing version.

Also, I tried the large number group prj file on three versions of CRHM. See the following.

1. srlab crhmcode CRHM_GUI for Issue#442:
This version fixed issue for group ending AZ, BZ, CZ, DZ, etc.; now variables under these groups are displayed in variable panel.
There is issue for Macro; that is, I cannot add any new code in the existing macro code in Macro Dialog window. I can only delete the existing macro code.
When running the group prj file, there is warning about "200 inputs... " as @jhs507 described. When prj finished run, CRHM_GUI crashed without any output being saved successfully.

2. srlab crhmcode CRHM_GUI release version 1.3.4:
There is issue for group group ending AZ, BZ, CZ, DZ, etc.; the above version fixed this. So, this is good.
Same issue with Macro Dialog window, as described above.

3. Borland CRHM:
No issue with group ending AZ, BZ, CZ, DZ, etc.
No issue with Macro Dialog window, I can add or delete code from Macro Dialog window.
The group prj can run in very slow speed in Borland CRHM, but no crash.

**Comment by loganxingfang** [comment]
I think Issue 442 for CRHM_GUI is fixed and can be closed.

Crash at the end for CRHM_GUI, this is to do with saving too many variables, as @jhs507 mentioned "I would advise attempting to run this in CRHMcode gcc or without using the GUI to see if it can produce expected results as CRHMcode GUI is not intended to be able to display so many outputs on the graph". So, this is not to do with Issue 442.

The Macro Dialog window should be dealt as a separate issue. @liudilena can you open a new issue for that?

**Comment by liudilena** [comment]
OK. I would open a new issue for the Macro Dialog window. Thanks. @loganxingfang @jhs507

**Comment by jhs507** [comment]
I have merged the pull request and will close this issue.
